---
- include_vars: "{{ ansible_os_family }}.yml"
- name: Install epel-release
  package:
    name: epel-release
    state: present
  when:  ansible_os_family == 'RedHat'
- name: Install nginx
  package:
    name: nginx
    state: present
- name: Copy template conf nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
    
- name: Ensures /etc/nginx/sites-available/ dir exists
  file: path=/etc/nginx/sites-available state=directory
  
- name: Install virtual hosts conf
  template:
    src: site.j2
    dest: "/etc/nginx/sites-available/{{ item }}"
    force: yes
  loop: "{{ hostname }}"
  
- name: Ensures /var/www/html/{{ item }} dir exists
  file: path=/var/www/html/{{ item }}  state=directory
  loop: "{{ hostname }}"
  
- name: Ensures /etc/nginx/sites-enabled/ dir exists
  file: path=/etc/nginx/sites-enabled state=directory

- name: Start service
  service:
    name: nginx
    enabled: yes
    state: started
    
- name: Enable virtual host
  file:
    src:  "/etc/nginx/sites-available/{{ item }}"
    path: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  loop:
    "{{ hostname }}"
  notify: restart nginx

- include_tasks: "{{ ansible_os_family }}.yml"

