---
- hosts: web
  become: yes
  tasks:
  - name: Install nginx
    import_role:
      name: nginx
  - name: Install ssl cert
    import_role:
      name: sslcert
  - name: Ensures for exist dir
    file:
      path: "~{{user}}/.ssh"
      state: directory
    become_user: "{{user}}"
  - name: Copy ssh private key
    copy:
      content: "{{ ssh_private_key}}"
      dest: "~{{user}}/.ssh/id_rsa"
    become_user: "{{user}}"

