---
# tasks file for sslcert
- name: Enable epel repo
  yum:
    name: epel-release
    state: present

- name: Install certbot
  yum: 
    name: certbot, python2-certbot-nginx
    state: present

- name: Issues certificate
  shell: "certbot --non-interactive --agree-tos -m nevgin@yandex.ru --nginx -d {{domain}}"

- name: Enable https on firewall
  firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled
- name: Add to cron renew certificate 
  cron:
    cron_file: certbot
    user: root
    name: "renew certificate"
    minute: "0"
    hour: "0,12"
    job: "certbot renew"

