---
# tasks file for sslcert
- name: Enable epel repo
  yum:
    name: epel-release
    state: present

- name: Enable https on firewall
  firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled
- name: Ensures ssl dir exist
  file:
    path: /etc/nginx/ssl
    state: directory
- name: Copy ssl private key
  copy:
    content: "{{ ssl_private_key }}"
    dest: "/etc/nginx/ssl/{{ ssl_hostname }}.key"
- name: Copy ssl fullchain.key
  copy: 
    content: "{{ ssl_fullchain }}"
    dest: "/etc/nginx/ssl/{{ ssl_hostname }}.crt"
- name: Adding ssl configuration to virtualhost
  template:
    src: ssl.conf.j2
    dest: "/etc/nginx/ssl/{{ ssl_hostname }}.conf"
- name: Copy dhparams
  copy:
    src: ssl-dhparams.pem 
    dest: /etc/nginx/ssl/ssl-dhparams.pem

