---
- name: Install key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Install_repo
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu xenial nginx
